repos:
  # pylint 需要本地安装
  - repo: local
#  - repo: https://github.com/pycqa/pylint
#    rev: v3.1.0
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          []

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
